### ISSUE TITLE
active_interfaces() can't find primary interface and IP of Debian 9 container (LXD)

### ISSUE THREAD

**Issue by kpapad904** [webmin/webmin#1184]
Please note that the latest Webmin 1.941 / Virtualmin 6.08 still have problems identifying the primary network interface and IP of Debian containers running under LXD and need us to manually input it every time. Same problem 6 months ago.

Virtualization: LXD
Host Operating System: Ubuntu 18.04 LTS
Guest Operating System: Debian 9.11
Kernel: Linux 4.15
Architecture: x86-64

ip addr output inside the Debian containers looks like this:
5: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
168: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
etc

# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
168: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:50:56:00:f2:99 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 95.xxx.yy.59/28 brd 95.xxx.yy.63 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2002:aaaa:bbbb::cccc:7a3b/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::aaa:bbbb:cccc:f299/64 scope link 
       valid_lft forever preferred_lft forever

# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 95.xxx.yy.59  netmask 255.255.255.240  broadcast 95.xxx.yy.63
        inet6 fe80::aaa:bbbb:cccc:f299  prefixlen 64  scopeid 0x20<link>
        inet6 2002:aaaa:bbbb::cccc:7a3b  prefixlen 64  scopeid 0x0<global>
        ether 00:50:56:00:f2:99  txqueuelen 1000  (Ethernet)
        RX packets 40897  bytes 7007976 (6.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34759  bytes 7295612 (6.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 509  bytes 61458 (60.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 509  bytes 61458 (60.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

#

**Comment by kpapad904** [comment]
In addition to not auto-detecting the "Network interface for virtual addresses" in Virtualmin Configuration, after we manually define it as eth0, it still doesn't autodetect the associated IPv4 requires us to manually define it in "Default virtual server IPv4 address".

So unless with manually provide both the network interface name and its IP, the Re-Check Configuration will give errors that the system is not ready for use with Virtualmin.

PS: I hope that hard-coding the virtual server IPv4/IPv6 addresses doesn't complicate issues if the Virtualmin server needs to be moved.

**Comment by jcameron** [comment]
OK, I just checked in a fix (linked about) that should fix this.

**Comment by kpapad904** [comment]
Hi and thanks for promptly looking into this.

You should add a "+" after the \d (/^\d+:\s+) at the beginning, because that number gets up to 3 digits (it's 168 in my test system, as indicated in my initial post).

Regarding the overall regexp, the following regexp has been working for me ([a-z]+).:
/^\d+:\s+([a-z]+\d+)@([a-z]+\d+):/

**Comment by kpapad904** [comment]
Just a quick reminder that the fix committed 10 days ago doesn't work on my test LXC systems.

I have been using the following regexp instead, which works fine:
/^\d+:\s+([a-z]+\d+)@([a-z]+\d+):/

**Comment by NuxRo** [comment]
Thanks @kpapad904, your regexp worked for me too.

**Comment by kpapad904** [comment]
Please note that the problem remains and I still have to patch the code as follows:

diff /usr/share/webmin/net/linux-lib.pl /usr/share/webmin/net/linux-lib.pl-orig
41c41
< 		elsif ($l =~ /^\d+:\s+([a-z]+\d+)@([a-z]+\d+):/) {
---
> 		elsif ($l =~ /^\d:\s+([^ \t\r\n\@]+\d+)@([^ \t\r\n\@]+\d+):/) {

**Comment by paulocoghi** [comment]
@kpapad904 , it seems that Webmin team only added the "+" you asked, but the full regexp is still not working for us, with `venet0:0` interface.

https://github.com/webmin/webmin/blob/395d7d261dd7adc9d6f045d3c41596f5e80eb0cd/net/linux-lib.pl#L35-L43

**Comment by paulocoghi** [comment]
@kpapad904 , is your regexp still working? Because if it is, I'm thinking in propose a PR.

**Comment by iliajie** [comment]
> it seems that Webmin team only added the "+" you asked, but the full regexp is still not working for us, with venet0:0 interface.

What is the output of `ip addr` command on your system?

**Comment by paulocoghi** [comment]
The output of `ip addr` is:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/void 
    inet 127.0.0.1/32 scope host venet0
       valid_lft forever preferred_lft forever
    inet 54.39.193.10/24 brd 54.39.193.255 scope global venet0:0
       valid_lft forever preferred_lft forever
```

**Comment by paulocoghi** [comment]
Webmin/Virtualmin wrongly recognizes `127.0.0.1` from `venet0` as our main/public IP

**Comment by iliajie** [comment]
> 2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default

This already should be caught by `^\d+:\s+([^ \t\r\n\@]+):` (second regex).


@jcameron 
> Webmin/Virtualmin wrongly recognizes `127.0.0.1` from `venet0` as our main/public IP

Jamie, don't we use external IP over local, if both are caught? Is this a bug?

@paulocoghi 
Also, can we see the screenshot from Webmin UI with detected network interfaces, both active and on boot?

**Comment by paulocoghi** [comment]
Sure! Here it is:

First, `127.0.0.1` is presented as the main/public IP on Virtualmin Dashboard:

![webmin-01-home](https://user-images.githubusercontent.com/378397/221182851-40e57c79-5d9e-48ff-918a-dc8704413712.png)

And here are the active and on boot network interfaces:

**[active]**

![webmin-network-active](https://user-images.githubusercontent.com/378397/221183121-36aaf6ae-83c4-4ede-860c-ed537f1c47f3.png)

**[on boot]**

![webmin-network-boot](https://user-images.githubusercontent.com/378397/221183158-81a56665-0543-4771-9bb3-a3b5e14a8d37.png)

**Comment by iliajie** [comment]
> First, `127.0.0.1` is presented as the main/public IP on Virtualmin dashboard:

Alright, what displayed on the dashboard is a separate issue. Also, I don't see any issues in **Network Interfaces** module.

Please give [this patch](https://github.com/webmin/authentic-theme/commit/7353a1ae319c961b0deeca2a727187fed2fac45d) a try. Does it show the correct IP now?

**Comment by paulocoghi** [comment]
I'm probably doing something wrong. My steps to apply the patch:

- edited `/usr/share/webmin/authentic-theme/authentic-lib.pl` and applied exactly the same [patch](https://github.com/webmin/authentic-theme/commit/7353a1ae319c961b0deeca2a727187fed2fac45d)

- restarted `webmin` with `service webmin restart` _(as root)_

- clicked on `Theme Configuration` -> `Clear Cache`

Still `127.0.0.1`, but your patch seems correct.

**Comment by paulocoghi** [comment]
But also the installer isn't able to identify the public IP for cases such `venet0:0`, be it automatically or even after asking for the public interface.

**Comment by iliajie** [comment]
> But also the installer isn't able to identify the public IP for cases such `venet0:0`,

What is the output of the following commands:

```
# 1
ip ro ls|grep default|head -1|sed -e 's/.*\sdev\s//g'|awk '{print $1}'

# 2
defaultdev=$(ip ro ls|grep default|head -1|sed -e 's/.*\sdev\s//g'|awk '{print $1}')
ip -f inet addr show dev "$defaultdev" | grep 'inet ' | awk '{print $2}' | head -1 | cut -d"/" -f1 | cut -f1

```

**Comment by paulocoghi** [comment]
The output is:

1
```bash
# ip ro ls|grep default|head -1|sed -e 's/.*\sdev\s//g'|awk '{print $1}'
venet0
```

2
```bash
# defaultdev=$(ip ro ls|grep default|head -1|sed -e 's/.*\sdev\s//g'|awk '{print $1}')
# ip -f inet addr show dev "$defaultdev" | grep 'inet ' | awk '{print $2}' | head -1 | cut -d"/" -f1 | cut -f1
127.0.0.1
```

**Comment by iliajie** [comment]
> 2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
>     link/void 
>     inet 127.0.0.1/32 scope host venet0
>        valid_lft forever preferred_lft forever
>     inet 54.39.193.10/24 brd 54.39.193.255 scope global venet0:0
>        valid_lft forever preferred_lft forever

I don't see the point in having this loopback address 127.0.0.1/32 on this interface!

**Comment by paulocoghi** [comment]
I agree with you.

But unfortunately this is the new default for OpenVZ and, despite this behavior being possibly modifiable, other users may receive their servers in this way.

**Comment by iliajie** [comment]
I'm actually surprised that you're seeing this wrong IP displayed at all.

Could you show the screenshot of Network Interfaces according from the Dashboar, e.g.:

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/4426533/221564068-16153ddb-c8b1-4f0a-862e-84480508d386.png">

**Comment by paulocoghi** [comment]
Sure! Here it is:

![webmin-network-interfaces](https://user-images.githubusercontent.com/378397/221565359-d654b869-4f49-4f88-8071-e6ca755ce2f6.png)

**Comment by iliajie** [comment]
Alright, I think this patch would work for you. Please give it a try:

https://github.com/webmin/authentic-theme/commit/04d9d0e7a9a8ec5f834acd163d29d1de8333479e

**Comment by paulocoghi** [comment]
I will test it right now :)

**Comment by paulocoghi** [comment]
Still `127.0.0.2`, but I believe your patch **is** correct. Do you suggest any extra steps beyond the steps below?

- apply your last patch on `/usr/share/webmin/authentic-theme/authentic-lib.pl`
- restart webmin with `service webmin restart` _(as root)_
- trigger the `Clear Cache` on `Theme Configuration`

**Comment by paulocoghi** [comment]
O checked twice that my `/usr/share/webmin/authentic-theme/authentic-lib.pl` is now exactly equal to your last patch https://github.com/webmin/authentic-theme/commit/04d9d0e7a9a8ec5f834acd163d29d1de8333479e

**Comment by iliajie** [comment]
> * apply your last patch on `/usr/share/webmin/authentic-theme/authentic-lib.pl`
> * restart webmin with `service webmin restart` _(as root)_
> * trigger the `Clear Cache` on `Theme Configuration`

No, great job.

> Still 127.0.0.1, but I believe your patch is correct.

Then it's coming from `$info->{'ips'}` .. ? Try replacing the following line from the patch:

```
my $ip = $info && $info->{'ips'} ? $info->{'ips'}->[0]->[0] : $ip_detect;
```

with

```
my $ip = $ip_detect;
```

**Comment by paulocoghi** [comment]
Trying it right now

**Comment by paulocoghi** [comment]
Update: nope. Still 127.0.0.1. Here is the screenshot of the last changes on `authentic-lib.pl`

![last-changes](https://user-images.githubusercontent.com/378397/221594399-9a12934f-03c3-412e-b8d1-04544504392d.png)

I'm starting to feeling bad, because you are working so hard! If you want, I can create a temporary sudoer user for you.

**Comment by iliajie** [comment]
> I'm starting to feeling bad, because you are working so hard! If you want, I can create a temporary sudoer user for you.

No need for this. Thank you.

**Comment by iliajie** [comment]
Alright! What is the output of the following commands:

```
cat /etc/hostname
cat /etc/resolv.conf | grep -E "search|domain"
cat /etc/hosts | grep "10.211.55.56"
hostname
hostname -f
hostnamectl | grep hostname
```

🙂

**Comment by paulocoghi** [comment]
Here it is!

```
cat /etc/hostname
h2foz.com.br

cat /etc/resolv.conf | grep -E "search|domain"
# all known uplink DNS servers. This file lists all configured search domains.

cat /etc/hosts | grep "10.211.55.56"

hostname
h2foz.com.br

hostname -f
h2foz.com.br

hostnamectl | grep hostname
   Static hostname: h2foz.com.br
```

**Comment by paulocoghi** [comment]
```
cat /etc/resolv.conf

# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 213.186.33.99
```

**Comment by paulocoghi** [comment]
```
cat /etc/hosts

127.0.0.1 h2foz.com.br h2foz
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
```

**Comment by paulocoghi** [comment]
It seems that `/etc/hosts` may be the problem, because of the line

```
127.0.0.1 h2foz.com.br h2foz
```

**Comment by iliajie** [comment]
> cat /etc/hosts | grep "10.211.55.56"

By that I meant:
```
cat /etc/hosts | grep "54.39.193.10"
```

> 127.0.0.1 h2foz.com.br h2foz


Try replacing it with:

```
127.0.0.1       localhost h2foz
54.39.193.10 h2foz.com.br
```

**Comment by iliajie** [comment]
@jcameron 
Paulo, despite of which results you get, Jamie why do we care about `/etc/hosts` if there is a `hostnamectl` command to get the hostname?

**Comment by paulocoghi** [comment]
> By that I meant:

Sorry. It was a stupid move on my part. I realize only later. :face_with_spiral_eyes: 

> Yeah, try replacing it with:

Now the IP `54.39.193.10` shows on the dashboard

**Comment by iliajie** [comment]
No, problem. However, let's see what Jamie says. I don't think it's reasonable nowadays to rely on `/etc/hosts` if we have `hostnamectl` and/or `hostname -f` .. at least `get_system_hostname` should have a flag to prioritize actual hostname returned by commands above.

> For some reason, authentic-lib.pl gives precedence for the IPs on /etc/hosts over the ones defined on the network configuration

This is not Authentic, as it relies on Webmin API for getting hostname and IP address.

**Comment by paulocoghi** [comment]
> This is not Authentic, as it relies on Webmin API for getting hostname and IP address.

Thanks for the info!

**Comment by iliaross** [comment]
❗️ If the issue isn't resolved, feel free to reopen it with updated details.
