### ISSUE TITLE
CPU Temps not showing for AMD Ryzen Threadripper 3970X.

### ISSUE THREAD

**Issue by PetroBHayes** [webmin/webmin#1484]
```
Operating system: CentOS Linux 7.9.2009
Webmin version: 1.974
Authentic theme version: 19.75 
Kernel and CPU: Linux 3.10.0-1160.25.1.el7.x86_64 on x86_64
Processor information: AMD Ryzen Threadripper 3970X 32-Core Processor, 64 cores
```
```
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: Micro-Star International Co., Ltd.
        Product Name: Creator TRX40 (MS-7C59)
        Version: 1.0
```

```
# sensors
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +53.4Â°C  (high = +70.0Â°C)

iwlwifi-virtual-0
Adapter: Virtual device
temp1:            N/A

max1617-i2c-13-4d
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +39.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-14-4d
Adapter: SMBus PIIX4 adapter port 2 at 0b00
temp1:        +39.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-15-4d
Adapter: SMBus PIIX4 adapter port 3 at 0b00
temp1:        +39.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-16-4d
Adapter: SMBus PIIX4 adapter port 4 at 0b00
temp1:        +39.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)
```

**Comment by jcameron** [comment]
@iliaross can you take a look at this? It looks like you most recently updated the code to detect CPU temps on Ryzen.

**Comment by iliarostovtsev** [comment]
Fixed - https://github.com/webmin/webmin/commit/7fe97a751fb9357006c5759b85abc9587ff37eb6

**Comment by iliarostovtsev** [comment]
> temp1:        +53.4Â°C temp1:        +39.0Â°C .. 

It looks that you're having encoding issues in your shell.

**Comment by PetroBHayes** [comment]
Sorry about the munged characters.  Looks like that happens if you use putty through RDP.  I've attached a corrected version just in-case.  Thanks for looking into it.
[sens.txt](https://github.com/webmin/webmin/files/6491277/sens.txt)

**Comment by iliarostovtsev** [comment]
> Sorry about the munged characters. Looks like that happens if you use putty through RDP. I've attached a corrected version just in-case. Thanks for looking into it.

The patch above will work. Thanks.

**Comment by PetroBHayes** [comment]
Using the latest version of webmin didn't fix this issue:

`Operating system: CentOS Linux 7.9.2009
Webmin version: 1.979 	
Authentic theme version: 19.81 
Kernel and CPU: Linux 3.10.0-1160.31.1.el7.x86_64 on x86_64
Processor information: AMD Ryzen Threadripper 3970X 32-Core Processor, 64 cores	`

Here's the "sensors >sens.bin" from my system saved and transferred as binary.  Note: the github webUI won't let me upload a *.bin file, so I've renamed it to sens_bin.txt.  Looking at the HEX view of the file, the degree symbol is encoded using 2 bytes, 0xC2 and 0xB0.  I tried to manually grep sensors using the new line from /proc/linux-lib.pl and it seems to work.

`sensors | grep -P "temp(\d+):\s+([\+\-][0-9\.]+).*?Â°[Cc]\s+.*?[=+].*?\)"
temp1:        +53.0Â°C  (high = +70.0Â°C)
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
`
So I'm not sure what's wrong.
Thanks for any help.

[sens_bin.txt](https://github.com/webmin/webmin/files/6681179/sens_bin.txt)

**Comment by iliarostovtsev** [comment]
What is the full output of `sensors` command?

**Comment by PetroBHayes** [comment]
The attached sens_bin.txt file in the message above is the full output.  I'll quote a copy here also and hope characters don't get corrupted.

```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +67.5Â°C  (high = +70.0Â°C)

iwlwifi-virtual-0
Adapter: Virtual device
temp1:            N/A  

max1617-i2c-13-4d
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-14-4d
Adapter: SMBus PIIX4 adapter port 2 at 0b00
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-15-4d
Adapter: SMBus PIIX4 adapter port 3 at 0b00
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-16-4d
Adapter: SMBus PIIX4 adapter port 4 at 0b00
temp1:        +38.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)
```
Thanks!

**Comment by iliarostovtsev** [comment]
Thanks for reporting. Give this patch a try, please - 

https://github.com/webmin/webmin/commit/939c8eb4fe61b4580816e0ec3e301eaa3c898602

**Comment by PetroBHayes** [comment]
No, it still doesn't work.  Looking at that section of code a bit more, I don't think it's the degree character.
```
                        # New line - new device (disallow, if no either fan or
                        # voltage data)
                        $aa = 0 if (/^\s*$/);

                        # Device has either fan or voltage data (sign of CPU)
                        $aa = 1 if (/fan[\d+]:\s+[0-9]+\s+RPM/i ||
                                    /in[\d+]:\s+[\+\-0-9\.]+\s+V/i);
```
The thread ripper sensors output doesn't include any fan or voltage data in the output, so the "if ($aa && " in the temp parsing is failing before it ever gets to parse out the degree symbol.

I just tried running sensors-detect again and running scans for every device I could, it still shows the exact same output as the attached file, with just one CPU temp.  I know there are a bunch of fans inside that system too, which is a little sad that I'm not able to get info for those either.

**Comment by iliarostovtsev** [comment]
.. so, this part:

~~~
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +67.5Â°C  (high = +70.0Â°C)

iwlwifi-virtual-0
Adapter: Virtual device
temp1:            N/A  
~~~

is completely unrelated to CPU?

**Comment by iliarostovtsev** [comment]
Does your _sensor_ command provide CPU temps at all?

**Comment by PetroBHayes** [comment]
The k10temp-pci-00c3 I believe is the CPU temp sensor.  There are other sensors on the motherboard, temp, fan and voltage that would normally be displayed, but are apparently not currently supported for the Super IO chip used by my ThreadRipper motherboard.  Here's the output from the sensors-detect that I believe shows the missing kernel driver that I need:
```
Trying family `VIA/Winbond/Nuvoton/Fintek'...               Yes
Found unknown chip with ID 0xd451
```
I believe the nct6775 kernel driver may have some support for my system, so I'm currently trying to figure out how to get it to load.

**Comment by PetroBHayes** [comment]
Well, I was able to get my fan speed and voltages to show up in the sensors output, but it still won't show a temperature in webmin.  :(

```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +51.6Â°C  (high = +70.0Â°C)

iwlwifi-virtual-0
Adapter: Virtual device
temp1:            N/A

max1617-i2c-13-4d
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +37.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-14-4d
Adapter: SMBus PIIX4 adapter port 2 at 0b00
temp1:        +37.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-15-4d
Adapter: SMBus PIIX4 adapter port 3 at 0b00
temp1:        +37.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

max1617-i2c-16-4d
Adapter: SMBus PIIX4 adapter port 4 at 0b00
temp1:        +37.0Â°C  (low  =  +0.0Â°C, high = +85.0Â°C)
temp2:          FAULT  (low  =  +0.0Â°C, high = +85.0Â°C)

nct6797-isa-0a20
Adapter: ISA adapter
in0:                    +1.25 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +0.98 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                    +3.38 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                    +3.34 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                    +1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +0.15 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +0.72 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                    +3.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                    +3.28 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                    +1.84 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +0.68 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +0.67 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +0.99 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +0.68 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +1.54 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                  2253 RPM  (min =    0 RPM)
fan2:                  1091 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
fan6:                     0 RPM  (min =    0 RPM)
fan7:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +40.0Â°C  (high = +80.0Â°C, hyst = +75.0Â°C)  sensor = CPU diode
CPUTIN:                 +35.0Â°C  (high = +112.0Â°C, hyst = +85.0Â°C)  sensor = thermistor
AUXTIN0:                +41.5Â°C  (high = +112.0Â°C, hyst = +85.0Â°C)  sensor = thermistor
AUXTIN1:                +44.0Â°C    sensor = thermistor
AUXTIN2:                +44.0Â°C    sensor = thermistor
AUXTIN3:                 -3.0Â°C    sensor = thermistor
SMBUSMASTER 0:          +51.5Â°C
PCH_CHIP_CPU_MAX_TEMP:   +0.0Â°C
PCH_CHIP_TEMP:           +0.0Â°C
PCH_CPU_TEMP:            +0.0Â°C
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled
```

**Comment by iliarostovtsev** [comment]
Which line(s) exactly on the output above represent CPU temperature?

**Comment by PetroBHayes** [comment]
The k10temp-pci-00c3:temp1 temperature is the main temp reported by the CPU.  It doesn't require installing extra drivers.  However it apparently has reliability issues: https://wiki.archlinux.org/title/lm_sensors#Troubleshooting  

The nct6797-isa-0a20 sensors only showed up on my system when I activated https://elrepo.org/ and installed the nct6775 driver from that repo.  These are sensors that are provided by the motherboard and I'm not exactly sure how they relate to the actual CPU temperature.  Just from my own evaluation, I can see the number that most closely matches the k10temp is the SMBUSMASTER_0 temperature.  The SYSTIN temp say's it's a CPU diode, and seems reasonable as a cpu temp, but is much lower than the k10temp.  The CPUTIN temp seems very low and almost never changes, so I'm not sure what that's measuring.

I wish I had a better answer for you as to which temp to read.  I think the k10temp sensors is the best one, since it doesn't require extra drivers and would give the broadest support.

**Comment by PetroBHayes** [comment]
By modifying the code to ignore the fan and voltage requirement I was able to get the temperature to show up in webmin.
```
                        $aa = 1 if (/k10temp-pci-00c3$/);
                        # Device has either fan or voltage data (sign of CPU)
                        #$aa = 1 if (/fan[\d+]:\s+[0-9]+\s+RPM/i ||
                        #           /in[\d+]:\s+[\+\-0-9\.]+\s+V/i);

                        # Get odd output like in #1253
                        if ($aa && (
                                /temp(\d+):\s+([\+\-][0-9\.]+)\s+.*?[=+].*?\)/ ||
                                /temp(\d+):\s+([\+\-][0-9\.]+).*?[Cc]\s+.*?[=+].*?\)/
                        )) {
                                # Adjust to start from `0` as all other outputs
                                push(@rvx, { 'core' => (int($1) - 1),
                                             'temp' => $2 });
                                }
```

**Comment by iliarostovtsev** [comment]
> The CPUTIN temp seems very low and almost never changes, so I'm not sure what that's measuring.

This the the temperature read from the CPU sensor on the MB. We need _CoreTemp_ data. This _sensors_ command output is just odd in my opinion.

Check this patch - https://github.com/webmin/webmin/commit/76591fab0a695d6a60d6bb1246033afe2484301f - replace the whole file to avoid typos.

**Comment by PetroBHayes** [comment]
Yup, that works.  It says Core2 for some reason, but I don't care about that.
![Capture](https://user-images.githubusercontent.com/73912983/123164295-9d220e80-d427-11eb-9914-4f2a7e09002b.jpg)

Thanks for all the help!

**Comment by iliarostovtsev** [comment]
Check this patch out - https://github.com/webmin/webmin/commit/d10e122cea7f1c803dbca9fbe34572db2cecaad5

**Comment by PetroBHayes** [comment]
Ok, says Core 1 now.  

Thanks!

**Comment by iliarostovtsev** [comment]
Cool server!

**Comment by chris001** [comment]
Because of all the non-standardized names/numbers of temp sensors, many temp displaying apps let the user pick which temp sensor to display, in case the app logic guesses "incorrectly"... For an app as an example, on the PC/Windows, the app "Speedfan"...

**Comment by iliarostovtsev** [comment]
I was thinking of adding it but it would require an extra configuration option but we already have so many.

**Comment by coderexpress** [comment]
CPU Temps not showing on MSI B550, with Ryzen 5600
sensors cmd output:

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +27.0 C  
Tccd1:        +23.8 C  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +24.9 C  (low  = -273.1 C, high = +84.8 C)
                       (crit = +89.8 C)

nct6687-isa-0a20
Adapter: ISA adapter
VIN0:               1.01 V  (min =  +0.00 V, max =  +0.00 V)
VIN1:               1.02 V  (min =  +0.00 V, max =  +0.00 V)
VIN2:             976.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN3:             592.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN4:             944.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN5:               1.04 V  (min =  +0.00 V, max =  +0.00 V)
VIN6:             896.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN7:               1.55 V  (min =  +0.00 V, max =  +0.00 V)
VCC:                3.34 V  (min =  +0.00 V, max =  +0.00 V)
VTT:                1.84 V  (min =  +0.00 V, max =  +0.00 V)
fan1:              789 RPM  (min =    0 RPM)
fan2:                0 RPM  (min =    0 RPM)
fan3:                0 RPM  (min =    0 RPM)
fan4:             1534 RPM  (min =    0 RPM)
fan5:                0 RPM  (min =    0 RPM)
fan6:                0 RPM  (min =    0 RPM)
fan7:                0 RPM  (min =    0 RPM)
fan8:                0 RPM  (min =    0 RPM)
fan9:                0 RPM  (min =    0 RPM)
fan10:               0 RPM  (min =    0 RPM)
AMD TSI Addr 98h:  +27.0 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = AMD AMDSI
Diode 0 (curr):    +28.5 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = thermal diode
Thermistor 15:     +25.0 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = thermistor
Thermistor 1:      +32.0 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = thermistor
Thermistor 16:     +24.5 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = thermistor
Thermistor 0:      +23.5 C  (low  =  +0.0 C)
                            (high =  +0.0 C, hyst =  +0.0 C)
                            (crit =  +0.0 C)  sensor = thermistor
Thermistor 15:     +25.0 C  (low  =  +0.0 C)
                            (high = +120.0 C, hyst = +33.0 C)
                            (crit =  +0.0 C)  sensor = thermistor
intrusion0:       ALARM
beep_enable:      disabled

the motherboard uses this kernel module  nct6683 to access the motherboard sensors. 

Thank you in advance
