### ISSUE TITLE
Not all fans collected and displayed in dashboard

### ISSUE THREAD

**Issue by Nekomich** [webmin/webmin#2517]
Hey,

i had installed a corsair commander pro to control all fans within my home server. Due to many disk i have currently seven case fans and one cpu fan.
In webmin dashboard only the 3 fans appear which are connected to the motherboard an no fan from the corsair commander pro.
I already change name of the fans listet by corsair commander pro with a config file in /etc/sensors.d/ to match name schemata `fan(\d)+`.
In addition i checked if sensors lines match `/(?|fan([\d+])\s*:\s*([0-9]+)\s*rpm|cpu(\s)fan\s*:\s*([0-9]+)\s*rpm|cpu\s+fan\s*:\s*([0-9]+)\s*rpm)/i` from [linux-lib.pl](https://github.com/webmin/webmin/blob/master/proc/linux-lib.pl#L495-L645) and they do.

I'm sadly not able to understand PERL code.

My system:
Ubuntu Linux 24.04.2
Intel i5 10500T
ASRock B560 Steel Legend
Corsair Commander Pro
13 HDD + 1 NVME

```
$ sensors

corsaircpro-hid-3-1
Adapter: HID adapter
in0:          12.11 V
in1:           5.04 V
in2:           3.40 V
fan1:         999 RPM
fan2:        1798 RPM
fan4:        1010 RPM
fan5:        1450 RPM
fan6:        1522 RPM

drivetemp-scsi-0-b0
Adapter: SCSI adapter
temp1:        +35.0°C  (low  =  +5.0°C, high = +55.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +36.0°C)

drivetemp-scsi-0-50
Adapter: SCSI adapter
temp1:        +37.0°C  (low  =  +0.0°C, high = +65.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +30.0°C, highest = +37.0°C)

drivetemp-scsi-0-90
Adapter: SCSI adapter
temp1:        +33.0°C  (low  = +10.0°C, high = +40.0°C)
                       (crit low =  +5.0°C, crit = +60.0°C)
                       (lowest = +26.0°C, highest = +36.0°C)

drivetemp-scsi-0-30
Adapter: SCSI adapter
temp1:        +38.0°C  (low  =  +0.0°C, high =  +0.0°C)
                       (crit low =  +0.0°C, crit =  +0.0°C)
                       (lowest = +29.0°C, highest = +38.0°C)

drivetemp-scsi-0-70
Adapter: SCSI adapter
temp1:        +34.0°C  (low  =  +5.0°C, high = +55.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +38.0°C)

drivetemp-scsi-0-10
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +0.0°C, high = +60.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +36.0°C)

nct6798-isa-0290
Adapter: ISA adapter
in0:                   696.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.69 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                     3.44 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                     3.44 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                     1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                     1.07 V  (min =  +0.00 V, max =  +0.00 V)
in6:                     1.19 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                     3.42 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                     3.25 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                     1.07 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                    1.04 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                  944.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                  904.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                    1.26 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                    1.70 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan0:                     0 RPM  (min =    0 RPM)
cpu fan:                372 RPM  (min =    0 RPM)
fan0:                     0 RPM  (min =    0 RPM)
cha_cpu fan7:           956 RPM  (min =    0 RPM)
fan0:                     0 RPM  (min =    0 RPM)
fan0:                     0 RPM  (min =    0 RPM)
hdd_uh fan3:           1362 RPM  (min =    0 RPM)
SYSTIN:                 +34.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit =  +0.0°C)  sensor = thermistor
CPUTIN:                 +33.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit = +100.0°C)  sensor = thermistor
AUXTIN0:                +16.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit = +100.0°C)  sensor = thermistor
AUXTIN1:                +23.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit =  +0.0°C)  sensor = thermistor
AUXTIN2:                +28.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit =  +0.0°C)  sensor = thermistor
AUXTIN3:                -15.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit =  +0.0°C)  sensor = thermistor
PECI Agent 0:           +32.0°C  (high = +80.0°C, hyst = +75.0°C)
AUXTIN4:                +22.0°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit =  +0.0°C)
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C
PCH_CHIP_TEMP:           +0.0°C
PCH_CPU_TEMP:            +0.0°C
PCH_MCH_TEMP:            +0.0°C
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

nvme-pci-0100
Adapter: PCI adapter
Composite:    +34.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

drivetemp-scsi-0-c0
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +5.0°C, high = +55.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +36.0°C)

drivetemp-scsi-0-60
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +0.0°C, high = +60.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +28.0°C, highest = +36.0°C)

drivetemp-scsi-0-a0
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +5.0°C, high = +55.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +36.0°C)

drivetemp-scsi-0-40
Adapter: SCSI adapter
temp1:        +39.0°C  (low  = +10.0°C, high = +25.0°C)
                       (crit low =  +0.0°C, crit = +70.0°C)
                       (lowest = +30.0°C, highest = +39.0°C)

drivetemp-scsi-0-80
Adapter: SCSI adapter
temp1:        +34.0°C  (low  =  +5.0°C, high = +55.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +35.0°C)

drivetemp-scsi-0-20
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +0.0°C, high = +60.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +26.0°C, highest = +36.0°C)

drivetemp-scsi-0-0
Adapter: SCSI adapter
temp1:        +36.0°C  (low  =  +0.0°C, high = +60.0°C)
                       (crit low = -40.0°C, crit = +70.0°C)
                       (lowest = +27.0°C, highest = +36.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +32.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +32.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:        +30.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:        +29.0°C  (high = +80.0°C, crit = +100.0°C)
Core 4:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 5:        +29.0°C  (high = +80.0°C, crit = +100.0°C)
```

<img width="1854" height="724" alt="Image" src="https://github.com/user-attachments/assets/e9467fdf-8bde-4239-8207-3a69277b1393" />

**Comment by jcameron** [comment]
@iliaross could you take a look at this one? I think you worked on this code most recently..

**Comment by iliaross** [comment]
Yeah, thanks, Jamie! I’ll take look and update this ticket with progress…

**Comment by iliaross** [comment]
@Nekomich Basically, do you want information on chassis fans? If so, they shouldn't be added to the CPU fans column. We might consider creating a separate column for chassis fans, but I'm not sure about it yet.

Also, I reviewed how we currently match CPU fans. There were many non-CPU and other types of fans included. I've fixed that, and from now on, we'll only match those described in this commit https://github.com/webmin/webmin/commit/afa9e9bd385775c624d1f18e3da54be433c40892.

For systems without a clear "cpu_fan" label that still have CPU fans, manual labeling will be required from now on, using the `/etc/sensors.d/local.conf` file.

I'll close this issue now. If you want chassis fans displayed, open a new ticket, and we'll discuss it separately.

If you want some fans displayed on the dashboard already, apply the patch below and do custom relabeling as mentioned above for all the fans you want to include manually.

```
webmin patch https://github.com/webmin/webmin/commit/afa9e9b
```

**Comment by UweLoyal** [comment]
I think this works not for Pi5B!

pi@RASPBERRY-Pi5B:~ $ sensors
rp1_adc-isa-0000
Adapter: ISA adapter
in1:           1.46 V
in2:           2.52 V
in3:           1.16 V
in4:           1.21 V
temp1:        +57.8°C

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +52.9°C

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A

pwmfan-isa-0000
Adapter: ISA adapter
fan1:        3176 RPM


How should the /etc/sensors.d/local.conf look like in my case?
Or what I hve to to with my sensor command output to show in WebMin Monitor?

The Patch only has no effect in my System.

Rgds
   Uwe

**Comment by iliaross** [comment]
> How should the /etc/sensors.d/local.conf look like in my case?

Try the following:

```
~# nano /etc/sensors.d/raspberrypi.conf
```

Add the following content to it:

```
# CPU temp
chip "cpu_thermal-virtual-*"
    label temp1 "CPU"

# Fan
chip "pwmfan-isa-*"
    label fan1 "cpu fan 1"
```

Re-run `sensors` command.

```
~# sensors
```

This will re-label it to work correctly with Webmin on Raspberry Pi.

**Comment by UweLoyal** [comment]
Still no effect:

No CPU-Temp, no RPM

<img width="2773" height="942" alt="Image" src="https://github.com/user-attachments/assets/ad2644fe-aaf4-45d5-a4f3-1aa5c0c1b525" />

pi@RASPBERRY-Pi5B-UL1:~ $ sensors
pwmfan-isa-0000
Adapter: ISA adapter
cpu fan 1:      0 RPM

cpu_thermal-virtual-0
Adapter: Virtual device
CPU:          +50.1°C

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A

rp1_adc-isa-0000
Adapter: ISA adapter
in1:           1.46 V
in2:           2.53 V
in3:           1.37 V
in4:           1.38 V
temp1:        +57.2°C

**Comment by iliaross** [comment]
Ah, maybe also we just need to hide the other rails too. Try adding more to the config we created:

```
# Hide adc-isa
chip "rp1_adc-isa-*"
    ignore in1
    ignore in2
    ignore in3
    ignore in4
    label temp1 "RP1"   # optional

# Hide volt-isa
chip "rpi_volt-isa-*"
    ignore in0
    ignore in0_lcrit_alarm
```

and, re-run `sensors` command.

**Comment by UweLoyal** [comment]
All gone away 
:(

<img width="2795" height="893" alt="Image" src="https://github.com/user-attachments/assets/c970a338-e8a4-4a72-a0e9-22410ecedd94" />

pi@RASPBERRY-Pi5B-UL1:~ $ sensors
rp1_adc-isa-0000
Adapter: ISA adapter
RP1:          +57.8°C

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +49.6°C

rpi_volt-isa-0000
Adapter: ISA adapter

pwmfan-isa-0000
Adapter: ISA adapter
fan1:           0 RPM

pi@RASPBERRY-Pi5B-UL1:~ $


PS: Wenn ich alles zurücknehme, dann erscheint wieder die CPU-Temperatur

**Comment by iliaross** [comment]
Can you show the content of your `/etc/sensors.d/raspberrypi.conf` file?

**Comment by UweLoyal** [comment]
I'll tryed yourconfig again, here Config and Results:


/etc/sensors.d/raspberrypi.conf:

`# Hide adc-isa
chip "rp1_adc-isa-*"
    ignore in1
    ignore in2
    ignore in3
    ignore in4
    label temp1 "RP1"   # optional

# Hide volt-isa
chip "rpi_volt-isa-*"
    ignore in0
    ignore in0_lcrit_alarm

`

Sensor:
pi@RASPBERRY-Pi5B-UL1:~ $ sensors
rpi_volt-isa-0000
Adapter: ISA adapter

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +51.2°C

rp1_adc-isa-0000
Adapter: ISA adapter
RP1:          +58.4°C

pwmfan-isa-0000
Adapter: ISA adapter
fan1:           0 RPM

pi@RASPBERRY-Pi5B-UL1:~ $


<img width="2777" height="934" alt="Image" src="https://github.com/user-attachments/assets/bf21ceb7-29ef-4b43-a6a9-22702d4bbf21" />

Correct Temperature:

cpu_thermal-virtual-0
Adapter: Virtual device
temp1: +51.2°C

**Comment by UweLoyal** [comment]
<img width="2777" height="934" alt="Image" src="https://github.com/user-attachments/assets/8d697d88-e250-4507-95ca-7766af441c0d" />

**Comment by iliaross** [comment]
That doesn't look right!

Try:

```
# CPU Temp
chip "cpu_thermal-virtual-*"
    label temp1 "CPU Temp"

# CPU Fan
chip "pwmfan-isa-*"
    label fan1 "CPU Fan"

# Hide the noise we don't care about
chip "rp1_adc-isa-*"
    ignore temp1
    ignore in1
    ignore in2
    ignore in3
    ignore in4

chip "rpi_volt-isa-*"
    ignore in0
    ignore in0_lcrit_alarm
```

and re-run `sensors` command.

I'm afraid I'll have to find a way to support those Pi sensors too.

**Comment by UweLoyal** [comment]
pi@RASPBERRY-Pi5B-UL1:~ $ sensors
rpi_volt-isa-0000
Adapter: ISA adapter

cpu_thermal-virtual-0
Adapter: Virtual device
CPU Temp:     +50.7°C

rp1_adc-isa-0000
Adapter: ISA adapter

pwmfan-isa-0000
Adapter: ISA adapter
CPU Fan:        0 RPM

pi@RASPBERRY-Pi5B-UL1:~ $

<img width="2772" height="937" alt="Image" src="https://github.com/user-attachments/assets/40b95403-35a9-441d-b9bd-2ff3699f24a3" />

**Comment by UweLoyal** [comment]
<img width="2782" height="1001" alt="Image" src="https://github.com/user-attachments/assets/1f258c96-8513-4899-98f6-d27931b73419" />

Line was first after switch on of Fan included (maybe of the Refresh of Side)

Thanks for Help!

**Comment by iliaross** [comment]
> Zeile wurde erst nach einschalten des Lüfters eingeblendet (ggf. auch des Refreshs)

Yeah, you need to update it using the force-refresh button after that change.

I think I need to solve it another way. I doubt users can sort it out on their own. I'll update this ticket with the progress...

**Comment by UweLoyal** [comment]
Additional Info:
You have to reboot after bugfix implementation

Found it out after correcting second Pi5B

Is it possible to fix without using  /etc/sensors.d/raspberrypi.conf ?

**Comment by iliaross** [comment]
It's been implemented. Apply the following patch and give it another try:

```
webmin patch https://github.com/webmin/webmin/commit/1453508
```

**Comment by UweLoyal** [comment]
Thank's for excellent cooperation.!

Am I correct in understanding that now only the fix (webmin patch https://github.com/webmin/webmin/commit/1453508) is applied and thus the use of /etc/sensors.d/raspberrypi.conf is no longer necessary.

That would like my whish abouve.

Rgds
Uwe Loyal

**Comment by iliaross** [comment]
Yes, that's right, no need for a custom config.

**Comment by UweLoyal** [comment]
Sorry, still no info at new Bugfix:

pi@RASPBERRY-Pi5B-UL1:~ $ sensors
pwmfan-isa-0000
Adapter: ISA adapter
fan1:        3334 RPM

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +54.5°C

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A

rp1_adc-isa-0000
Adapter: ISA adapter
in1:           1.46 V
in2:           2.53 V
in3:           1.12 V
in4:           1.14 V
temp1:        +58.4°C

pi@RASPBERRY-Pi5B-UL1:~ $

<img width="2778" height="941" alt="Image" src="https://github.com/user-attachments/assets/6b0c9b74-740f-444a-97d0-2bd2b8427f15" />

**Comment by UweLoyal** [comment]
Do you have an idea why Monitor shows RPMs and Sensor's nothing?


pi@RASPBERRY-Pi5B-UL1:~ $ sensors
pwmfan-isa-0000
Adapter: ISA adapter
fan1:           0 RPM

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +50.7°C

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A

rp1_adc-isa-0000
Adapter: ISA adapter
in1:           1.46 V
in2:           2.52 V
in3:           1.09 V
in4:           1.11 V
temp1:        +58.4°C

pi@RASPBERRY-Pi5B-UL1:~ $


<img width="2780" height="994" alt="Image" src="https://github.com/user-attachments/assets/74879e63-9af7-45a8-ad1a-68c519057491" />

Ok, if longer off this is shown:

<img width="2770" height="932" alt="Image" src="https://github.com/user-attachments/assets/77a94c35-cb4d-4be7-b005-a63811a6d810" />

How long is the Updateinterval?

**Comment by iliaross** [comment]
> Do you have an idea why Monitor shows RPMs and Sensor's nothing?

Check this patch https://github.com/webmin/webmin/commit/a73210adc9b16ef21eb1aedc5cea52a1a044e716 out.

**Comment by UweLoyal** [comment]
Ok, shows Fan Speed, but also long time after Fan stops, with changes values, like it would be cached.
Any idea?

**Comment by iliaross** [comment]
No, it should be updated constantly if real-time monitoring in the theme settings is enabled.

**Comment by UweLoyal** [comment]
Ok, seems to be Problem of Chrome, with Firefox all works fine!
Chrome is my Standard Browser, too many open tabs, a bad habit of mine! 😎

**Comment by UweLoyal** [comment]
on second Pi5B this is shown, is there a Problem?

`pi@RASPBERRY-Pi5B:~ $ sudo webmin patch https://github.com/webmin/webmin/commit/a73210a
Patch failed: Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From a73210adc9b16ef21eb1aedc5cea52a1a044e716 Mon Sep 17 00:00:00 2001
|From: Ilia Ross <ilia@ross.gdn>
|Date: Sat, 6 Sep 2025 18:51:36 +0300
|Subject: [PATCH] Fix to show FAN even if RPM is zero
|
|---
| proc/linux-lib.pl | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/proc/linux-lib.pl b/proc/linux-lib.pl
|index e8c297f4b9..35e17a93b0 100755
|--- a/proc/linux-lib.pl
|+++ b/proc/linux-lib.pl
--------------------------
patching file proc/linux-lib.pl
Using Plan A...
Hunk #1 FAILED at 747.
1 out of 1 hunk FAILED -- saving rejects to file proc/linux-lib.pl.rej
done

pi@RASPBERRY-Pi5B:~ $`

**Comment by iliaross** [comment]
Please wait for the new Webmin 2.501 release.

**Comment by UweLoyal** [comment]
<img width="2776" height="994" alt="Image" src="https://github.com/user-attachments/assets/4a3f6c34-b999-4f4c-a1a3-ee4bb0632176" />

Works 👍

**Comment by UweLoyal** [comment]
Still problems with actualisation of Values.
Fan in running and Monitor shows 0 RPM
Maybe this is the Proble?

<img width="3833" height="361" alt="Image" src="https://github.com/user-attachments/assets/1de126a9-dc03-4549-9f00-c9422b05e1e3" />

<img width="3840" height="541" alt="Image" src="https://github.com/user-attachments/assets/3b2074b5-0d67-4958-8674-81ca0ee86fe0" />

Tested with Windows PC and iPhone with Chrome and Firefox.
Rgds
Uwe Loyal

**Comment by iliaross** [comment]
Please upgrade to the latest Webmin 2.501, and if you still have an issue open a new thread!
