### ISSUE TITLE
DNSSEC Subdomain Operations [Feature Request]

### ISSUE THREAD

**Issue by hsntgm** [webmin/webmin#512]
Hello @jcameron ,

When you create a subdomain in virtualmin while it has already DNSSEC signed upper zone you are able to cover subdomains with below simple actions. (must have DS records on domain registar)

Maybe virtualmin give a chance to select this option when you create Key for subdomains which has a already active DNSSEC setup.
 
Webmin > Bind Dns Server > zone > Setup DNSSEC Key  | with a new option like that: 

> ¶Automatically manage DS records for master zone.

> It seems you have upper zone which DNSSEC enabled for sub.example.com. Do you want to add DS records to Master Zone?

Process:

1) Subdomain need to has separate master zone for DNSSEC, so it has to be top level server in virtualmin. PS: I did not tried sub-server or alias options while creating virtual server for it.

2) Add subdomain DS records to upper zone. ( example.com) . 
You don't need to add these records to domain registrar. You have already these DS records for upper zone example.com on domain registrar. It means all subdomain DS records are under your control and you have to manage them manually.
e.g.
sub.example.com.	IN	DS	9613 5 1 697FA09DB82B413142A128....
sub.example.com.	IN	DS	9613 5 2 1B14F91F4BB1BF9ED60BACEB85107A6C3..

3) Add nameservers for subdomain to upper zone. ( example.com)
e.g.
sub.example.com.	IN	NS	ns1.example.com.
sub.example.com.	IN	NS	ns2.example.com.

You can check and verify this setup on my test server.

https://dnssec-debugger.verisignlabs.com/luksdekortadilat.com
https://dnssec-debugger.verisignlabs.com/forum.luksdekortadilat.com

Best Regards,

**Comment by jcameron** [comment]
Are you running the latest Virtualmin release (5.06 or above) there? Because it should already add DS records to parent domains if both the parent and sub-domain are in Virtualmin.

**Comment by hsntgm** [comment]
I am pretty sure i am on 5.06. Thanks for new update now i am about to upgrade 5.07. I manually added DS records for my subdomain. Do you have any positive feedback for this setup. I mean anybody tried to DNSSEC with subdomain and passed https://dnssec-debugger.verisignlabs.com and give you a feedback. In my case i am sure it doesn't work. 

Sincerely,

**Comment by hsntgm** [comment]
Update: I am now on 5.07 and if you select Yes for **Create DNSSEC key and sign new domains**? in server templates and create a top level subdomain it adds automatically DS records to parent zone. But if you don't choose it from server templates and manually sign subdomain in webmin bind module it doesn't add DS records.

Sincerely,

**Comment by jcameron** [comment]
Right, you'd have to do that manually. The webmin BIND module is for more expert users who know what records they need to add where :-)

**Comment by chris001** [comment]
I confirm @hsntgm this feature has had some hidden problems, which I've previously posted issues about here, the problems cause failure to verify at the verisign dnssec checker.

Note my setup however is not exactly pure DNSSEC on every dns server - using an external DNS service for slave dns and that dns service says they don't fully support all dnssec records.  Sometimes the dnssec checker probably randomly selects the external slave DNS servers and therefore likely fails verification because some records are possibly missing or not signed as expected.
Will try it on a virtual server domain with the external slave dns servers removed and see if it verifies as correct.

**Comment by hsntgm** [comment]
https://github.com/webmin/webmin/issues/511

I noticed that when you use NSEC3 algorithm to sign zone with webmin DNS module verisign dnssec checker fails. The detailed error says "no rrsig found for nameservers'. However [Dnsviz](http://dnsviz.net/) results say it's ok.

If all DNSSEC operations managed by bind utils @jcameron I wish you update bind module to 9.11 which brings new DNSSEC features. 

**DNSSEC Key Manager**

> Best practices for DNSSEC implementation require regular key rollovers.  This can be a maintenance burden and is now easily automated with a new utility.
> 
> dnssec-keymgr is meant to run unattended (e.g., under cron). It reads a policy definition file (default: /etc/dnssec.policy) and creates or updates DNSSEC keys as necessary to ensure that a zone’s keys match the defined policy for that zone. New keys are created whenever necessary to ensure rollovers occur correctly. Existing keys’ timing metadata is adjusted as needed to set the correct rollover period, prepublication interval, etc. If the configured policy changes, keys are corrected automatically. See the dnssec-keymgr man page for full details.

**ElephantsParent-child updating (DNSSEC information)**

> Another task associated with the DNSSEC KSK rollover is updating the parent zone with the new DS record, or DSKEY record. Today this is usually accomplished by manually filling in a web form. After much discussion in the industry, the consensus seems to be that the most flexible automated way to do this with adequate security, is to publish the information in the child zone, using DNSSEC to ensure the integrity of the information.
> 
> Following RFC 7344 Automating DNSSEC Delegation Trust Maintenance, Two new resource records, CDS and CDSKEY, are created and populated automatically for DNSSEC-signed zones, on the server that is authoritative for those zones. These ‘child’ records can be looked up by the parent, enabling the parent to update itself.

**Comment by chris001** [comment]
Fedora 26 has BIND 9.11.
Debian Jessie 8 lets you easily build BIND 9.11 from source and install it without disrupting the distro package BIND 9.9.  Just change the symlinks to point to the 9.11 version.  When the distro upgrades to BIND 9.11, you can point the symlinks back to the distro.
https://www.urspringer.de/2016/11/06/debian-jessie-upgrade-bind9-newer-version/
```
cd /usr/local/src
wget https://ftp.isc.org/isc/bind9/9.11.0-P3/bind-9.11.0-P3.tar.gz
tar zxvf bind-9.11.0.tar.gz
rm bind-9.11.0.tar.gz
cd bind-9.11.0/
./configure
make
make install
```

**Comment by chris001** [comment]
There's a problem with the Webmin BIND9 module.  Even after you install BIND-9.11.0-P3 from source as above, and the new version 9.11 is running (`ps` shows `/usr/local/sbin/named`, and `named -v` shows `BIND 9.11.0-P3 <id:4801fbc`, yet the Webmin module says BIND 9.9  ?!

**Comment by chris001** [comment]
It looks like I found a new corner case bug.  Is the Webmin BIND module assuming `/usr/sbin/named` is always the path to bind9??  Even when the startup script and systemd is starting `/usr/local/sbin/named` ??

Shouldn't Webmin dynamically figure out which bind started up, and obtain version info from that binary and use that path, instead of assuming the distro packaged version is running, because running the distro package is a false assumption when you're running a version built from source in `/usr/local/sbin` in order to obtain the latest CVE bug fixes and get the benefits of the new DNSSEC binary `dnssec-keymgr`.

**Comment by hsntgm** [comment]
@chris001 thank you for your feedback.
I will be honest i am afraid of to update bind module to 9.11.It is not easy task on my eye with webmin.I was pretty sure this attempt would break something and you confirmed it.So maybe @jcameron implement this uptade separatly or can share a guide for this uptade because it seems we can't see bind 9.11 update in the near future for many linux distro. 

Sincerely,

**Comment by chris001** [comment]
@hsntgm The link above, on urspringer.de, shows how to install bind 9.11 along side the existing bind 9 on debian 8.
It's simple, takes 5 minutes to install it manually.  Probably a script would do it in 30 seconds.

**Comment by hsntgm** [comment]
@chris001  

> There's a problem with the Webmin BIND9 module. Even after you install BIND-9.11.0-P3 from source as above, and the new version 9.11 is running (ps shows /usr/local/sbin/named, and named -v shows BIND 9.11.0-P3 <id:4801fbc, yet the Webmin module says BIND 9.9 ?!

I fixed that :
**BIND DNS Module Config > Full path to the named executable > /usr/local/sbin/named**

**Comment by chris001** [comment]
@jcameron Do you think it'd be possible to use of `dnssec-keymgr`, `CDS` and `CDSKEY` records, when a BIND version is installed which provides it, see RFC 7344, this automates key rollover, hash/key generation, and automate DS record propagation to your external DNS registrar, respectively.

**Comment by jcameron** [comment]
Yes, this is on my TODO list.

**Comment by chris001** [comment]
Some documents @jcameron to help the team get BIND 9.11 automated deployment of `DS` key using with `CDS` and `CDNSKEY`, methods described in IETF RFC7344 and RFC8078. 👍 
* https://www.isc.org/blogs/release-9-11-adds-provisioning-options-for-dns-authoritative-services/
* https://tools.ietf.org/html/rfc8078
* https://tools.ietf.org/html/rfc7344
* https://blog.apnic.net/2017/12/06/dnssec-deployment-remains-low/
* https://www.cloudflare.com/dns/dnssec/how-dnssec-works/
This is a perfect opportunity for Webmin, VirtualMin, to level up and join the ranks of the most secure DNS host on the internet, CloudFlare, and lead the push to secure DNSSEC everywhere with `BIND 9.11`'s `DNSSEC` automated `DS` key deployment through `RFC8078` `CDS` and `CDNSKEY`. 👍

**Comment by chris001** [comment]
Update!  21 Months later!  Time flies!

* Webmin/Virtualmin still fails to propagate `DS` records to parent zones that are either virtual servers or domains that it manages, or at least, it fails in some cases. This is a show stopper bug:

![virtualmin webmin bind fails to propagate ds records to parent zone](https://user-images.githubusercontent.com/259416/70927172-831a9b00-1ffc-11ea-80b8-8105b3515ec3.png)

* Webmin/Virtualmin (sometimes?) fails to remove expired `DNSKEY` key records. This is merely a warning, not a show stopper bug, however it makes zone transfers unnecessarily larger and could be sign of some more serious issue:

![virtualmin webmin expired rrsigs](https://user-images.githubusercontent.com/259416/70927208-90378a00-1ffc-11ea-89df-7ad09c22d7fa.png)

* Webmin/Virtualmin provides keys yet fails to sign all records with the keys it provided, in violation of the RFC. This is a show stopper bug:

![virtualmin webmin dnssec error found dnskey but no rrsigs for alg 8](https://user-images.githubusercontent.com/259416/70927188-8a41a900-1ffc-11ea-8348-22b894c7d0d4.png)

With DNSSEC, a show stopper bug is one that breaks secure name lookups for the domain, rendering web services on the domain inaccessible to the internet.

**Comment by hsntgm** [comment]
:) 21 Months !

I hope everything is better than 2 years ago.
`And merry christmas to all.`

**Comment by shoulders** [comment]
@chris001 has this one been fixed?

**Comment by chris001** [comment]
@shoulders 
When I create 1) New virtual top-level server, and 2) New Sub-server under an existing domain.
Both test domains pass ✔️  the full DNSSEC test on https://dnssec-debugger.verisignlabs.com/
System: Virtualmin 7.20.2, Webmin 2.202, BIND 9.18.28, Debian  GNU/Linux 12.

**Comment by iliaross** [comment]
❗️ If the issue isn't resolved, feel free to reopen it with updated details.
