### ISSUE TITLE
Serve webmin with subdirectory/contextPath

### ISSUE THREAD

**Issue by totomaze** [webmin/webmin#670]
Hi,
Is there an easy way to serve webmin with a prefix/baseUrl without having to use Apache or Nginx to rewrite the url?

eg:  http://myhost:10000/webmin/

Good Job

**Comment by chris001** [comment]
Probably `miniserv.pl` needs to be modified to handle that prefix/baseURL/subdirectory setting, because it's the only one listening on the webmin port 10000.

**Comment by swelljoe** [comment]
What would the use case of this be? (I mean, usually people want a prefix for running Webmin behind a proxy so other stuff can live on the same IP:port. I can't think of why it'd be useful for a dedicated Webmin server...since nothing else could live on /, anyway, and the Webmin web server pretty much only supports Webmin.)

**Comment by totomaze** [comment]
I made it work with the reverse proxy but when I do that I can't access to webmin directly (the old way).
Using the reverseProxy (nginx) with the recommended modifications in config and miniserv.conf and few 
rewrite in nginx (authenticated/images/*.cgi)
reverseProxy:port/webmin => webminServer:10000 => working
 webminServer:10000 => Not functionnal
 webminServer:10000/webmin => Not functionnal

If my reverseProxy fails I just want to have a fallback to use the direct access.

some other websites have the reverseProxy option and handle it pretty (couchpotato, kodi-chorus, deluge)

I may miss something in nginx config or in miniser.conf/config to make this working as expected.

**Comment by swelljoe** [comment]
Oh, OK, that makes sense. I don't know if it is possible currently.

**Comment by jcameron** [comment]
There is no way to run webmin under a subdirectory when access directly currently, sorry.

**Comment by gnadelwartz** [comment]
hm, with apache its working without problems. Can you post your miniserv.conf?
I can only guess that a firewall rule or a miniserv option prevent direct access on port 1000

**Comment by rouing** [comment]
&write_data("Location: $prot://$hostport$in{'page'}\r\n");
should be changed too
&write_data("Location: $prot://$host$in{'page'}\r\n");

and it works fine. You also need to change some things in usr/share/webmin. This is all the result of terrible hardcoding. I hope to find an alternative to webmin one day.

**Comment by wxrl** [comment]
So I had a lot of problems setting up webmin proxy_pass to a subfolder with nginx, and it cost me half day to figure out it was just the "/" after the subfolder name **CANNOT** be omitted...

Before I could solve the problem, I always got some "pure-text-ish" page when visiting **https://mydomain.com/webmin** without any css and image files applied. Also I could not login from that page.

After solving the problem, I did another FRESH install and configuration again and verified it works well - just the "/" cannot be forgotten (doing the fresh install & config is just for verifying the problem was not solved by anything else, as I have tried hundreds of setting combinations in nginx site conf file as well as webmin config and miniserv conf files...)

So here is my setup

debian/10.10, nginx/1.14.2 (installed from debian apt repo), webmin/1.979 (installed from webmin_1.979_all.deb https://www.webmin.com/download.html)

1. Download https://prdownloads.sourceforge.net/webadmin/webmin_1.979_all.deb and install it via dpkg
2. Verify webmin itself is working well by visiting https://localhost:10000 (through remote desktop)
3. Verify nginx is serving https://mydomain.com well (I use letsencrypt for nginx ssl)
4. Add following to the nginx site conf file for mydomain.com (e.g. **/etc/nginx/sites-available/mydomain.com**)
```
        location /webmin/ {
                proxy_pass http://localhost:10000/;
        }
```

PLEASE note here that the second slash '**/**' after the subfolder name in "**location /webmin/**" can NOT be omitted.

5. Modify **/etc/webmin/config** by adding the following at the bottom
```
webprefix=/webmin
webprefixnoredir=1
referers=mydomain.com
```
6. Modify **/etc/webmin/miniserv.conf** as below
`ssl=0`
by default ssl is set to 1
7. Restart the services as below and I could visit https://mydomain.com/webmin perfectly.
```
sudo service webmin restart
sudo service nginx restart
```

**Comment by hungdhm-0574** [comment]
@wxrl i try your setting, its look easy but it did work.
My site still get error with `/unauthenticated/css/bundle.min.css?19839999999999902 (404 not found)`

**Comment by jwilleke** [comment]
Having similar issues.

<img width="729" alt="Screen Shot 2022-02-27 at 07 35 00" src="https://user-images.githubusercontent.com/3616688/155882606-11a39607-642a-47be-a487-0ce3550efdb6.png">


 /etc/webmin/config added:
```
webprefix=/webmin
webprefixnoredir=1
referers=mydomain.real.com
```
nginx:
```
        location /webmin/ {
          # proxy_buffering off;
          proxy_pass http://localhost:10000/;
          # proxy_set_header Host $host;
          # proxy_set_header X-Forwarded-For $http_x_forwarded_for;
          # proxy_redirect http://$host:10000/ http://$host/webmin/;
        }
```

**Comment by iliaross** [comment]
❗️ If the issue isn't resolved, feel free to reopen it with updated details.
